
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresdb
        image: postgres:13.14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: pg-user
              name: postgres-secret        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pg-passowrd
              name: postgres-secret

---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgres #should match above label name
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 9376